# Generated by Django 5.1.2 on 2024-10-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0004_product_gender_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.AddField(
            model_name='product',
            name='material_bracelet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал браслета'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_korpus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал корпуса'),
        ),
    ]
