# Generated by Django 5.1.2 on 2024-10-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0005_remove_product_material_product_material_bracelet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес'),
        ),
    ]
