# Generated by Django 5.1.2 on 2024-10-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0006_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Размер'),
        ),
    ]
