# Generated by Django 5.1.2 on 2024-11-04 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0010_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='totembo.reviews', verbose_name='Родитель'),
        ),
    ]
