# Generated by Django 5.1.2 on 2024-11-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0015_alter_orderproducts_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='Номер заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('total_price', models.FloatField(default=0, verbose_name='Сумма чека')),
                ('completed', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='totembo.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Сохранённый заказ',
                'verbose_name_plural': 'Сохранённые заказы',
            },
        ),
        migrations.CreateModel(
            name='SaveOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=500, verbose_name='Название товара')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('product_price', models.FloatField(verbose_name='Цена товара')),
                ('final_price', models.FloatField(verbose_name='Сумма')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фото товара')),
                ('color_name', models.CharField(max_length=100, verbose_name='Цвет товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='totembo.saveorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказов',
            },
        ),
    ]
